* afistfullofash's Guix Config
This configuration contains everything needed to configure both my laptop and desktop from scratch using both [[https://guix.gnu.org/manual/en/html_node/System-Configuration.html][Guix System]] and [[https://guix.gnu.org/manual/en/html_node/Home-Configuration.html][Guix Home]].
Generally if something is needed before the user logs in, like the Window Manager etc it is in the system configuration.
If something is going to be used by the user as much as possible it is all handled in the home configuration.

** Home
The Emacs and StumpWM configurations are both done literately using org babel.
| Program | Config File Location               |
|---------+------------------------------------|
| Emacs   | [[file:home/files/emacs/init.org]]     |
| StumpWM | [[file:home/files/stumpwm/config.org]] |

These are both tangled into their respective init.el and init.lisp files by (org-tangle-file) when Guix Home Reconfigure is ran.


* Configure a new system
This requires that the channels [[https://github.com/afistfullofash/afistfullofash][afistfullofash]] and [[https://gitlab.com/nonguix/nonguix/][nonguix]] are available.

#+name: configure-channels
#+begin_src scheme :tangle ~/.config/guix/channels.scm
  (list (channel
          (name 'guix)
          (url "https://git.guix.gnu.org/guix.git")
          (branch "master")
          (introduction
            (make-channel-introduction
              "9edb3f66fd807b096b48283debdcddccfea34bad"
              (openpgp-fingerprint
                "BBB0 2DDF 2CEA F6A8 0D1D  E643 A2A0 6DF2 A33A 54FA"))))
        (channel
          (name 'afistfullofash)
          (url "https://github.com/afistfullofash/afistfullofash")
          (branch "main"))
        (channel
          (name 'nonguix)
          (url "https://gitlab.com/nonguix/nonguix")
          (branch "master")
          (introduction
            (make-channel-introduction
              "897c1a470da759236cc11798f4e0a5f7d4d59fbc"
              (openpgp-fingerprint
                "2A39 3FFF 68F4 EF7A 3D29  12AF 6F51 20A0 22FB B2D5")))))
#+end_src

#+name: reconfigure-system
#+begin_src sh
  sudo guix pull
  sudo guix system reconfigure ./${SYSTEM_TO_DEPLOY}.scm
#+end_src

#+name: reconfigure-home
#+begin_src sh
  guix home reconfigure ./home.scm
#+end_src
