#!/bin/sh
#
#
# kill-gremlins
# Kill all process's matching <name>
# This is very usefull for programs like:
# - steam
#
# usage: kill-gremlins <program-name>
#
#
kill -9 $(procs $1 | awk '{ print $1 }' | tail -n +3)
