backend = "glx";
vsync = true;

detect-client-opacity = true;

fading = true;
no-fading-openclose = true;
no-fading-destroyed-argb = true;

# Faster fades
fade-in-step = 0.06;
fade-out-step = 0.06;
fade-delta = 6;   # ms

transparent-clipping = true;

blur-background = true;
blur-background-fixed = true;
blur-background-frame = true;

blur-method = "dual_kawase";
blur-size = 1;
blur-strength = 2;
blur-deviation = 1.0;

dithered-present = true;
force-win-blend = true;

rules: ({
  match = "window_type = 'tooltip' || ! name~='' || override_redirect";
  fade = false;
  blur-background = false;
  transparent-clipping = false;
}, {
  match = "name = 'slop' || class_r = 'slop' || class_g = 'maim'";
  transparent-clipping = false;
  blur-background = false;
  fade = false;
})