[global]
    log_verbosity = "info"
    startup_notification = true
    geometry = "1918x182+5122+0"
    wrap_content = true
    font = "DejaVu Sans 15"
    template = """
    [{{app_name}}] <b>{{summary}}</b>\
    {% if body %} {{body}}{% endif %} \
    {% if now(timestamp=true) - timestamp > 60 %} \
        ({{ (now(timestamp=true) - timestamp) | humantime }} ago)\
    {% endif %}\
    {% if unread_count > 1 %} ({{unread_count}}){% endif %}
    """

[urgency_low]
    background = "#282A36"
    foreground = "#BD93F9"
    timeout = 5
    text = "low"

[urgency_normal]
    background = "#282A36"
    foreground = "#FF79C6"
    timeout = 10
    text = "normal"

[urgency_critical]
    background = "#282A36"
    foreground = "#FF5555"
    timeout = 0
    text = "critical"